server:
  port: 8081
  servlet:
    context-path: /mojefinance/api

spring:
  jpa:
    show-sql: false
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
#  sql:
#    init:
#      mode: always
#      data-locations:
#        - classpath:db/scripts/data.sql

external:
  api:
    ceska-sporitelna:
      base-url: https://webapi.developers.erstegroup.com/api/csas/sandbox
      token-path: /v1/sandbox-idp/token