spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mojefinance
    driver-class-name: org.postgresql.Driver
    username: ${db-username}
    password: ${db-password}

  ssl:
    bundle:
      pem:
        bank-mtls:
          keystore:
            certificate: classpath:certs/ceska-sporitelna-cert.pem
            private-key: classpath:certs/ceska-sporitelna-key.key

  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:8080/realms/mojefinance/protocol/openid-connect/token/introspect
          client-id: ${mojefinance-client-id}
          client-secret: ${mojefinance-client-secret}

external:
  oauth2:
    ceska-sporitelna:
      client-id: ${ceska-sporitelna-client-id}
      client-secret: ${ceska-sporitelna-client-secret}
      redirect-uri: http://localhost:5173/bank-callback